taxon_counts: [32, 64]#, 128]#, 256, 512, 1024, 2048]
replicates: 2
working_directory: "out"
sampling_window: 2.0
sample_count: 100
height_scale: 0.1
sequence_length: 1000
tasks: ["likelihood"]
benchmarkables: ["treeflow", "beagle_bito_direct", "jax"]